### ISSUE TITLE
Appcelerator SDK 4.0.0

### ISSUE THREAD

**Issue by adamkearsley** [FokkeZB/nl.fokkezb.drawer#40]
Hi.
When running on Appcelerator Studio SDK V4.0.0 RC i get the following error when running on my Android device (Lollipop 5.0)
It works ok when i downgrade the SDK to 3.5.1GA.

```
[ERROR] :  TiApplication: (main) [407,407] Sending event: exception on thread: main msg:java.lang.AbstractMethodError: abstract method "void org.appcelerator.titanium.TiActivityWindow.windowCreated(org.appcelerator.titanium.TiBaseActivity, android.os.Bundle)"; Titanium 4.0.0,2015/04/17 11:34,95cdb9d
[ERROR] :  TiApplication: java.lang.AbstractMethodError: abstract method "void org.appcelerator.titanium.TiActivityWindow.windowCreated(org.appcelerator.titanium.TiBaseActivity, android.os.Bundle)"
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:33)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:450)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:543)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  TiApplication: 	at android.app.Activity.performCreate(Activity.java:6283)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2642)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2756)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:145)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5940)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: main
[ERROR] :  AndroidRuntime: Process: com.myapp.v4, PID: 12100
[ERROR] :  AndroidRuntime: java.lang.AbstractMethodError: abstract method "void org.appcelerator.titanium.TiActivityWindow.windowCreated(org.appcelerator.titanium.TiBaseActivity, android.os.Bundle)"
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:33)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:450)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:543)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6283)
[ERROR] :  AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2642)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2756)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
[ERROR] :  AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  AndroidRuntime: 	at android.os.Looper.loop(Looper.java:145)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5940)
[ERROR] :  AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] :  AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
[ERROR] :  AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

**Comment by FokkeZB** [comment]
This is a module problem and I see you have done a PR already:

https://github.com/viezel/NappDrawer/pull/156
