### ISSUE TITLE
On android the app crash

### ISSUE THREAD

**Issue by ikalangita** [FokkeZB/nl.fokkezb.drawer#78]
Hello,

Thanks for the module which works fine on ios but on android :

```
[ERROR] :  TiApplication: (main) [880,26844] Sending event: exception on thread: main msg:java.lang.ClassCastException: java.lang.Object[] cannot be cast to org.appcelerator.titanium.proxy.TiViewProxy; Titanium 6.0.1,2016/12/19 16:51,undefined
[ERROR] :  TiApplication: java.lang.ClassCastException: java.lang.Object[] cannot be cast to org.appcelerator.titanium.proxy.TiViewProxy
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:237)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Is there any fix for this?

Thanks

**Comment by FokkeZB** [comment]
Sorry, I really need more context, like the view's XML. Please reopen when you have
